### ISSUE TITLE
Youtube Feed

### ISSUE THREAD

**Issue by NicoDreamzZ** [witochandra/webfeed#5]
Hey there, i dont know much about rss feeds...
Is there a way to also parse youtube feeds like this https://www.youtube.com/feeds/videos.xml?channel_id=UCKLxFmPc7WHoThSwK8g92Gg with your lib?

The format looks different from my websites rss feed and the parse function throws many errors when unsing the youtube rss feed.

Maybe you can help me :D

**Comment by NicoDreamzZ** [comment]
```Invalid argument(s): updated not found
#0      xmlGetString (package:webfeed/util/helpers.dart:10:7)
#1      new AtomFeed.parse (package:webfeed/domain/atom_feed.dart:46:19)
#2      NewsFeedFragmentState.getRssFeedItems (package:bdh_app/views/components/fragment_newsfeed.dart:143:32)
<asynchronous suspension>
#3      NewsFeedFragmentState._handleRefresh (package:bdh_app/views/components/fragment_newsfeed.dart:110:5)
<asynchronous suspension>
#4      NewsFeedFragmentState.initState (package:bdh_app/views/components/fragment_newsfeed.dart:25:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3787:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
#9      SingleChildRenderObjectElement.mount (package:flutter/src/widge<…>```

**Comment by witochandra** [comment]
Thanks for reporting this issue.

webfeed is expecting some fields to be there. I have made some changes to make those fields optional in `webfeed: ^0.3.0`
Also in this version, RSS Media is now supported, so you can extract more information from youtube feeds. :)
